apiVersion: v1
kind: ServiceAccount
metadata:
  name: deploy-robot
  namespace: default
automountServiceAccountToken: false
---
apiVersion: v1
kind: Secret
metadata:
  name: deploy-robot-secret
  annotations:
    kubernetes.io/service-account.name: deploy-robot
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deploy-robot-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deploy-robot-binding
subjects:
  - kind: ServiceAccount
    name: deploy-robot
    namespace: default
roleRef:
  kind: ClusterRole
  name: deploy-robot-role
  apiGroup: rbac.authorization.k8s.io
