apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment-dev
  labels:
    app: flask-app-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app-dev
  template:
    metadata:
      labels:
        app: flask-app-dev
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: flask-app-dev
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: flask-container
        image: hamzaarja/flask-app:{{IMAGE_TAG}}
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service-dev
spec:
  type: LoadBalancer
  selector:
    app: flask-app-dev
  ports:
    - port: 80 
      targetPort: 80
